[package]
name = "notebook"
description = "Your private notebook"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "1.0.66"
dioxus = "0.2.4"
dioxus-router = "0.2.3"

[target.'cfg(not(target_family = "wasm"))'.dependencies]
dioxus-desktop = "0.2.3"

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.11.1"
log = "0.4.17"
ndk-context = "0.1.1"
paste = "1.0.9"

[target.'cfg(target_family = "wasm")'.dependencies]
console_error_panic_hook = "0.1.7"
dioxus-web = "0.2.1"
wasm-logger = "0.2.0"

[patch.crates-io]
dioxus = { git = "https://github.com/dioxuslabs/dioxus", rev = "1e99e35" }
dioxus-desktop = { git = "https://github.com/dioxuslabs/dioxus", rev = "1e99e35" }
dioxus-web = { git = "https://github.com/dioxuslabs/dioxus", rev = "1e99e35" }
dioxus-router = { git = "https://github.com/dioxuslabs/dioxus", rev = "1e99e35" }
