[package]
name = "mynote"
version = "0.1.0"
edition = "2021"

[dependencies]
# local
model = { path = "./model" }
config = { path = "./config" }
db = { path = "./db" }
auth = { path = "./auth" }
session = { path = "./session" }
user = { path = "./user" }
note = { path = "./note" }
crud = { path = "./crud" }
# async framework
tokio = { version = "^1", features = ["full"] }
futures = "^0"
futures-util = "^0"
# web framework
warp = "^0"
rust-embed = { version = "^6", features = ["compression", "debug-embed"] }
warp-embed = "^0"
async-graphql = { version = "^3", features = ["chrono"] }
async-graphql-warp = "^3"
# interface definition
sea-orm = { version = "^0", default-features = false }
chrono = "^0"
serde = "^1"
serde_json = "^1"
async-trait = "^0"
base64 = "^0"

[workspace]
members = [
    "config",
    "crud",
    "db",
    "auth",
    "note",
    "password",
    "model",
    "user",
    "session",
]
