[package]
name = "auth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlx = { version = "0.5", features = [
    "runtime-tokio-native-tls",
    "sqlite",
    "migrate",
    "chrono",
    "time",
] }
db = { path = "../db" }
chrono = "0.4.19"
async-graphql = { version = "3.0.19", features = [] }
jwt-simple = "0.10.8"
bcrypt = "0.10"
thiserror = "1.0.30"
serde_json = "1.0.74"
serde = "1.0.133"
async-trait = "0.1.52"
