[package]
name = "crud"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "^0"
sea-orm = { version = "^0", default-features = false }
chrono = "^0"
futures = "^0"
futures-util = "^0"
