apiVersion: apps/v1
kind: Deployment
metadata:
  name: notebook
  namespace: notebook-staging
  labels:
    app: notebook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notebook
  template:
    metadata:
      labels:
        app: notebook
    spec:
      containers:
        - name: notebook
          image: docker.io/onichandame/notebook:staging
          ports:
            - containerPort: 80
