## must inherit all secrets from caller

name: Build
on:
  workflow_call:
    inputs:
      env:
        required: true
        description: environment for which the build runs (e.g. staging/production/...)
        type: string
    outputs:
      backend:
        value: ${{ jobs.build_backend.outputs.tag }}
      frontend:
        value: ${{ jobs.build_frontend.outputs.tag }}
jobs:
  build_backend:
    name: Build backend
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ inputs.env }}-backend
    steps:
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          file: backend.dockerfile
          tags: onichandame/notebook:${{ inputs.env }}-backend
  build_frontend:
    name: Build frontend
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ inputs.env }}-frontend
    steps:
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: onichandame
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          file: frontend.dockerfile
          tags: onichandame/notebook:${{ inputs.tag }}-frontend
