## must inherit all secrets from caller
name: Build
on:
  workflow_call:
    inputs:
      env:
        required: true
        description: environment for which the build runs (e.g. staging/production/...)
        type: string
    outputs:
      images:
        value: ${{ jobs.build_backend.outputs.tag }}
      frontend:
        value: ${{ jobs.build_frontend.outputs.tag }}
jobs:
  collect:
    name: Collect Apps
    runs-on: ubuntu-latest
    outputs:
      apps: ${{ steps.collect.outputs.apps }}
    steps:
      - name: Collect
        id: collect
        env:
          APPS: ${{ needs.collect.outputs.apps }}
        run: |
          echo "apps=$(ls apps | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
  build:
    name: Build Apps
    runs-on: ubuntu-latest
    needs:
      - collect
    strategy:
      fail-fast: true
      matrix:
        app: ${{ fromJson(needs.collect.outputs.apps) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          file: apps/${{ matrix.app }}/Dockerfile
          tags: onichandame/notebook:${{ inputs.env }}-${{ matrix.app }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
