name: Release
on:
  push:
    tags:
      - "v*"
jobs:
  release:
    name: Release binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # rust
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      # android
      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r22b
      - run: echo "NDK_HOME=${{ steps.setup-ndk.outputs.ndk-path }}" >> $GITHUB_ENV
      - run: echo "$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_PATH
      - run: rustup target add aarch64-linux-android
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target aarch64-linux-android
        env:
          RUSTFLAGS: -Clinker=aarch64-linux-android30-clang
      - run: tar -C target/aarch64-linux-android/release -zcf android-arm64.tar.gz mynote
      # linux
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - run: tar -C target/release -zcf linux-amd64.tar.gz mynote
      # windows
      - run: sudo apt install mingw-w64 -y
      - run: rustup target add x86_64-pc-windows-gnu
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target x86_64-pc-windows-gnu
      - run: tar -C target/x86_64-pc-windows-gnu/release -zcf windows-amd64.tar.gz mynote.exe
      # release
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "android-arm64.tar.gz,linux-amd64.tar.gz,windows-amd64.tar.gz"
          token: ${{ secrets.GITHUB_TOKEN }}
