name: Staging
on:
  push:
    branches:
      - "master"
jobs:
  #build:
  #  name: Build Image
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Setup QEMU
  #      uses: docker/setup-qemu-action@v2
  #    - name: Set up Docker Buildx
  #      uses: docker/setup-buildx-action@v2
  #    - name: Login to DockerHub
  #      uses: docker/login-action@v2
  #      with:
  #        username: ${{ secrets.DOCKERHUB_USERNAME }}
  #        password: ${{ secrets.DOCKERHUB_TOKEN }}
  #    - name: Build and push
  #      uses: docker/build-push-action@v3
  #      with:
  #        push: true
  #        tags: ${{ secrets.DOCKERHUB_USERNAME }}/notebook:staging
  deploy:
    name: Deploy
    #needs:
    #  - build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup gcloud
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDIER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
      - name: Setup kubectl
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: ${{ secrets.CLUSTER_NAME }}
          location: ${{ secrets.LOCATION }}
      - name: Test
        run: kubectl get node
